import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Providers } from "~/app/providers";
import { Header } from "~/app/_components/header";
import { type ReactNode } from "react";
import { Footer } from "~/app/_components/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <Providers>
            <Header />
            <main className="py-3">{children}</main>
            <Footer />
          </Providers>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
